export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_SUCCESS = "AGREGAR_PRODUCTO_SUCCESS";
export const AGREGAR_PRODUCTO_FAILURE = "AGREGAR_PRODUCTO_FAILURE";

export const FETCH_PRODUCTOS = "FETCH_PRODUCTOS";
export const FETCH_PRODUCTOS_SUCCESS = "FETCH_PRODUCTOS_SUCCESS";
export const FETCH_PRODUCTOS_FAILURE = "FETCH_PRODUCTOS_FAILURE";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_FAILURE = "DELETE_PRODUCT_FAILURE";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const START_PRODUCT_EDITION = "START_PRODUCT_EDITION";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAILURE = "EDIT_PRODUCT_FAILURE";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
